package nl.queuemanager.core.jms;

public enum JMSFeature {
	FORWARD_MESSAGE,
	QUEUE_MESSAGES_SIZE,
	QUEUE_CAPACITY,
	QUEUE_CLEAR_MESSAGES,
    QUEUE_DELETE_MESSAGES,
	JMS_HEADERS,
	TOPIC_SUBSCRIBER_CREATION,
	DESTINATION_TYPE_QUEUE,
	DESTINATION_TYPE_TOPIC,
	MESSAGE_SET_PRIORITY;
}
