name: Package Mac App

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: Package
      run: sh -c package-mac.sh
