name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v3
      - name: Build fat jar
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: messagemanager-app:fatJar
      - uses: actions/upload-artifact@v3
        with:
          name: Message Manager Fat Jar
          path: messagemanager-app/build/libs/messagemanager-4*.jar

  package:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: Message Manager Fat Jar
        path: build/fatjar
    - name: Package Mac
      if: matrix.os == 'macos-latest'
      run: sh package-mac.sh
    - name: Package Windows
      if: matrix.os == 'windows-latest'
      run: .\package-win.bat
    - uses: actions/upload-artifact@v3
      with:
        name: Message Manager ${{ matrix.os }}
        path: build/install/*
